### ISSUE TITLE
Example app

### ISSUE THREAD

**Issue by dmckminard** [thruthesky/fireflutter#12]
This project looks very interesting!

But the app example link is no longer valid, would it be possible to have a demo code to see FireFlutter's features?

**Comment by thruthesky** [comment]
Yes, we have. Here it is: https://github.com/thruthesky/example

We are actively working on it for the new version.

**Comment by dmckminard** [comment]
The link doesn't work for me, maybe the project is private?

**Comment by thruthesky** [comment]
> The link doesn't work for me, maybe the project is private?

I will open the example project. And right now  we are actively working on it by rewriting the previous code. So we would like you to try it after a week or two weeks later.
