### ISSUE TITLE
pub get failed

### ISSUE THREAD

**Issue by salstein** [thruthesky/fireflutter#21]
iv'e been facing this error, trying to pub get the latest version of fireflutter (^0,0.41)

`Because every version of flutter_driver from sdk depends on path 1.6.4 and fireflutter >=0.0.5 depends on path ^1.7.0, flutter_driver from sdk is incompatible with fireflutter >=0.0.5.`

**Comment by thruthesky** [comment]
This definitely looks like an issue of dependency problem.

Try this and if the issue is solved.

```
flutter update-packages --force-upgrade
```

If not, can you upload your pubspec.yaml and `flutter doctor`?

**Comment by salstein** [comment]
It's the example app... I cloned the repository trying to pub get ...

**Comment by salstein** [comment]
issue resolved... i upgraded flutter to version 1.22.5

Thanks for your response...
