### ISSUE TITLE
Add `displayName, photoURL` on /meta/user/public

### ISSUE THREAD

**Issue by thruthesky** [thruthesky/fireflutter#24]
- Denormalization is the nature of Firebase
- Create `/meta/user/public/{uid}` when user register and put the user's displayName and photoURL by default.

**Comment by jtkeyva** [comment]
@thruthesky 
Is this completed?

I noticed your documentation references:
users/{uid}/meta/public

but firestore actually shows the data in:
meta/user/public/{uid}
