### ISSUE TITLE
Support Null Safety / SDK 2.12 / Flutter 2

### ISSUE THREAD

**Issue by jtkeyva** [thruthesky/fireflutter#32]
Hello,
Can you please update the package to support Null Safety / SDK 2.12 / Flutter 2?
Thanks!

**Comment by thruthesky** [comment]
@jtkeyva I really want to update it to support null safety but I can't find time for that now.
If there is anybody who want to update this project, It would be great.

**Comment by jtkeyva** [comment]
Got it I understand. I'll see what I can do and report back if I get it figured out so the package can be updated

**Comment by jtkeyva** [comment]
@fabiohxcx this is the other repo I tried to convert but had to revert back. Now I'm intimidated ha. Any help or guidance greatly appreciated.
These are the packages that I rely on that are not yet NULL Safe so it's kinda tricky:

simple_gravatar - looks like it’s updated as of github?
fireflutter - requested
merge_map - requested
esys_flutter_share (don’t need)
flutter_widgets - broken down into smaller packages that each support null safety
flutter_hsvcolor_picker
story_painter -reqeusted
fast_color_picker - requested
control_pad - requested
simple_timer - requested
cupertino_rounded_corners - requested

**Comment by thruthesky** [comment]
@jtkeyva Hmm.

I am not sure what to suggest :(
I feel like the `fireflutter` needs to be re-written many parts to support null safety.
I hope I can continue this work after my current project.

**Comment by riveraj33** [comment]
Hello. Any luck with updating this to support null safety and flutter 2.8?

**Comment by thruthesky** [comment]
> Hello. Any luck with updating this to support null safety and flutter 2.8?

@riveraj33 I am in another project now and have no time to update this. But if you are willing to participate, I am here to help. It should be re-rewritten over all for null safety. I will update the readme if somebody wants to take part in.

**Comment by jtkeyva** [comment]
@thruthesky thanks for checking in on this. i have moved from firebase to supabase so not sure how much i can be of help.
