### ISSUE TITLE
Documentation Not Clear

### ISSUE THREAD

**Issue by jbb-kryo** [thruthesky/fireflutter#35]
![image](https://user-images.githubusercontent.com/61083145/168819073-6e2f6bfa-4b4f-403b-91de-a03f3f9142d6.png)

I am following your instructions to get a test instance running. I am uncertain what it means by:
`Add the latest version of fireflutter into pubspec.yaml`

The second instruction concerning a podfile for firestore and firebase auth is also unclear. I cannot find either file that this seems to reference?

**Comment by thruthesky** [comment]
Hi @jbb-kryo 
I am sorry for the unclearness.
I meant, "Update platform version in Podfile".
The pod file under ios folder.
Thank you.

**Comment by thruthesky** [comment]
@jbb-kryo Hope this package help you :)
